version: 2.0

workflows:
  version: 2

  commit-workflow:
    jobs:
      - playwright/run
      
  schedule-workflow:
    triggers:
      - schedule:
          cron: "0 21 * * 1-5"
          filters:
            branches:
              only:
                - main
    jobs:
      - playwright/run

jobs:
  playwright/run:
    docker:
      - image: mcr.microsoft.com/playwright:bionic
        environment:
          NODE_ENV: development # Needed if playwright is in `devDependencies`
    steps:
      - checkout
      - run: npm install
      - run:
          name: E2E test
          command: npx playwright test general.spec.ts