version: 2.0
workflows:
  version: 2
  build:
    jobs:
      - playwright/run

executors:
  e2e:
    docker:
      - image: mcr.microsoft.com/playwright:next
        environment:
          NODE_ENV: development 
    working_directory: ~/workspace

jobs:
  playwright/run:
    executor: e2e
    steps:
      - checkout
      - run: npm install
      - run:
          name: E2E test
          command: npx playwright test general.spec.ts